/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import domain.MoveObject;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author marca
 */
public class Principal extends javax.swing.JFrame {
    
    
    private int position_tachometer = 0;
    private boolean barrer = false;
    private boolean barrer_carri_1=false;
    private boolean barrer_carri_2=false;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        loadImage();
        setLocationRelativeTo(null);
        //this.setExtendedState(MAXIMIZED_BOTH);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Lb_Speedometer = new javax.swing.JLabel();
        Btn_Gas_Brake = new javax.swing.JButton();
        Btn_Brake = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Lb_Car = new javax.swing.JLabel();
        btn_Barrer = new javax.swing.JButton();
        btn_carril_2 = new javax.swing.JButton();
        btn_carril_1 = new javax.swing.JButton();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(Lb_Speedometer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 720, 150, 150));

        Btn_Gas_Brake.setBackground(new java.awt.Color(0, 162, 232));
        Btn_Gas_Brake.setBorder(null);
        Btn_Gas_Brake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Gas_BrakeActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Gas_Brake, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 750, 70, 120));

        Btn_Brake.setBackground(new java.awt.Color(0, 162, 232));
        Btn_Brake.setBorder(null);
        Btn_Brake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BrakeActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Brake, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 800, 70, 70));

        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        jButton1.setText("Create");
        jButton1.setBorder(null);
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 890, 300, 70));
        getContentPane().add(Lb_Car, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, 120, 120));

        btn_Barrer.setBackground(new java.awt.Color(0, 162, 232));
        btn_Barrer.setBorder(null);
        btn_Barrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_BarrerActionPerformed(evt);
            }
        });
        getContentPane().add(btn_Barrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 730, 240, 130));

        btn_carril_2.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_2.setBorder(null);
        btn_carril_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 360, 65, 40));

        btn_carril_1.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_1.setBorder(null);
        btn_carril_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 360, 65, 40));

        jFondo.setFocusable(false);
        jFondo.setRequestFocusEnabled(false);
        jFondo.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 995));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Gas_BrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Gas_BrakeActionPerformed
        // TODO add your handling code here:
        int new_position_tachomer = position_tachometer+1;
        if(new_position_tachomer<3){
            position_tachometer=position_tachometer+1;
            ImageIcon speedometer = new ImageIcon("src/Assets/speedometer_icon_"+position_tachometer+".png");
            Icon iconoSpeedometer = new ImageIcon(speedometer.getImage().getScaledInstance(Lb_Speedometer.getWidth(), Lb_Speedometer.getHeight(), Image.SCALE_DEFAULT));
            Lb_Speedometer.setIcon(iconoSpeedometer);
            ImageIcon car = new ImageIcon("src/Assets/car_icon_"+position_tachometer+".png");
            Icon iconoCar = new ImageIcon(car.getImage().getScaledInstance(Lb_Car.getWidth(), Lb_Car.getHeight(), Image.SCALE_DEFAULT));
            Lb_Car.setIcon(iconoCar);
        }
        else {
            System.out.println("Alcanzo la velocidad maxima");
        }
        
    }//GEN-LAST:event_Btn_Gas_BrakeActionPerformed

    private void Btn_BrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BrakeActionPerformed
        // TODO add your handling code here:
        int new_position_tachomer = position_tachometer;
        if(new_position_tachomer>0){
            position_tachometer=position_tachometer-1;
            ImageIcon speedometer = new ImageIcon("src/Assets/speedometer_icon_"+position_tachometer+".png");
            Icon iconoSpeedometer = new ImageIcon(speedometer.getImage().getScaledInstance(Lb_Speedometer.getWidth(), Lb_Speedometer.getHeight(), Image.SCALE_DEFAULT));
            Lb_Speedometer.setIcon(iconoSpeedometer);
            ImageIcon car = new ImageIcon("src/Assets/car_icon_"+position_tachometer+".png");
            Icon iconoCar = new ImageIcon(car.getImage().getScaledInstance(Lb_Car.getWidth(), Lb_Car.getHeight(), Image.SCALE_DEFAULT));
            Lb_Car.setIcon(iconoCar);
        }
        else {
            System.out.println("Alcanzo la velocidad minima");
        }
    }//GEN-LAST:event_Btn_BrakeActionPerformed

    private void btn_BarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_BarrerActionPerformed
        // TODO add your handling code here:
        if(barrer==false){
            barrer=true;
            ImageIcon barrer = new ImageIcon("src/Assets/open_toll_icon.png");
            Icon iconBarrer = new ImageIcon(barrer.getImage().getScaledInstance(btn_Barrer.getWidth(), btn_Barrer.getHeight(), Image.SCALE_DEFAULT));
            btn_Barrer.setIcon(iconBarrer);
        }else{
            barrer=false;
            ImageIcon barrer = new ImageIcon("src/Assets/close_toll_icon.png");
            Icon iconBarrer = new ImageIcon(barrer.getImage().getScaledInstance(btn_Barrer.getWidth(), btn_Barrer.getHeight(), Image.SCALE_DEFAULT));
            btn_Barrer.setIcon(iconBarrer);
        }
    }//GEN-LAST:event_btn_BarrerActionPerformed

    private void btn_carril_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_1ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_1==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrer-activate-line-icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_1.getWidth(), btn_carril_1.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_1.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_1=false;
        }else{
            ImageIcon carril1 = new ImageIcon("src/Assets/barrer-desactive-line-icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_1.getWidth(), btn_carril_1.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_1.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_1=true;
        }
    }//GEN-LAST:event_btn_carril_1ActionPerformed

    private void btn_carril_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_2ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_2==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrer-activate-line-icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_1.getWidth(), btn_carril_1.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_2.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_2=false;
        }else{
            ImageIcon carril1 = new ImageIcon("src/Assets/barrer-desactive-line-icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_2.getWidth(), btn_carril_2.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_2.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_2=true;
        }
    }//GEN-LAST:event_btn_carril_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }
    
    public void loadImage(){
        
        ImageIcon fondo = new ImageIcon("src/Assets/background_icon_0.png");
        Icon iconoFondo = new ImageIcon(fondo.getImage().getScaledInstance(jFondo.getWidth(), jFondo.getHeight(), Image.SCALE_DEFAULT));
        jFondo.setIcon(iconoFondo);
        
        ImageIcon gasBrake = new ImageIcon("src/Assets/accelerator_icon.png");
        Icon iconoGasBrake = new ImageIcon(gasBrake.getImage().getScaledInstance(Btn_Gas_Brake.getWidth(), Btn_Gas_Brake.getHeight(), Image.SCALE_DEFAULT));
        Btn_Gas_Brake.setIcon(iconoGasBrake);
        
        ImageIcon brake = new ImageIcon("src/Assets/brake_icon.png");
        Icon iconoBrake = new ImageIcon(brake.getImage().getScaledInstance(Btn_Brake.getWidth(), Btn_Brake.getHeight(), Image.SCALE_DEFAULT));
        Btn_Brake.setIcon(iconoBrake);
        
        ImageIcon car = new ImageIcon("src/Assets/car_icon_0.png");
        Icon iconoCar = new ImageIcon(car.getImage().getScaledInstance(Lb_Car.getWidth(), Lb_Car.getHeight(), Image.SCALE_DEFAULT));
        Lb_Car.setIcon(iconoCar);
        
        ImageIcon speedometer = new ImageIcon("src/Assets/speedometer_icon_0.png");
        Icon iconoSpeedometer = new ImageIcon(speedometer.getImage().getScaledInstance(Lb_Speedometer.getWidth(), Lb_Speedometer.getHeight(), Image.SCALE_DEFAULT));
        Lb_Speedometer.setIcon(iconoSpeedometer);
        
        ImageIcon barrer = new ImageIcon("src/Assets/open_toll_icon.png");
        Icon iconBarrer = new ImageIcon(barrer.getImage().getScaledInstance(btn_Barrer.getWidth(), btn_Barrer.getHeight(), Image.SCALE_DEFAULT));
        btn_Barrer.setIcon(iconBarrer);
        ImageIcon barrer_lane = new ImageIcon("src/Assets/barrier_icon.png");
        Icon iconoCarril = new ImageIcon(barrer_lane.getImage().getScaledInstance(btn_carril_1.getWidth(), btn_carril_1.getHeight(), Image.SCALE_DEFAULT));
        btn_carril_1.setIcon(iconoCarril);
        btn_carril_2.setIcon(iconoCarril);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Brake;
    private javax.swing.JButton Btn_Gas_Brake;
    private javax.swing.JLabel Lb_Car;
    private javax.swing.JLabel Lb_Speedometer;
    private javax.swing.JButton btn_Barrer;
    private javax.swing.JButton btn_carril_1;
    private javax.swing.JButton btn_carril_2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jFondo;
    // End of variables declaration//GEN-END:variables
}
