/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import domain.MoveObject;
import java.awt.Image;
import java.util.TimerTask;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author marca
 */
public class Principal extends javax.swing.JFrame {
    
    
    private int position_tachometer = 0;
    private int cont=0;
    private boolean barrer = false;
    private boolean barrer_carri_1=false;
    private boolean barrer_carri_2=false;
    private boolean barrer_carri_3=false;
    private boolean barrer_carri_4=false;
    private boolean barrer_carri_5=false;
    private boolean barrer_carri_6=false;
    private boolean barrer_carri_7=false;
    private boolean barrer_carri_8=false;
    private boolean barrer_carri_9=false;
    private boolean barrer_carri_10=false;
    private boolean barrer_carri_11=false;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        loadImage();
        setLocationRelativeTo(null);
        //this.setExtendedState(MAXIMIZED_BOTH);
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Btn_Gas_Brake = new javax.swing.JButton();
        Btn_Brake = new javax.swing.JButton();
        Lb_Speedometer = new javax.swing.JLabel();
        Lb_Car = new javax.swing.JLabel();
        btn_create_car = new javax.swing.JButton();
        Btn_Barrer = new javax.swing.JButton();
        btn_carril_10 = new javax.swing.JButton();
        btn_carril_11 = new javax.swing.JButton();
        btn_carril_9 = new javax.swing.JButton();
        btn_carril_8 = new javax.swing.JButton();
        btn_carril_7 = new javax.swing.JButton();
        btn_carril_6 = new javax.swing.JButton();
        btn_carril_5 = new javax.swing.JButton();
        btn_carril_4 = new javax.swing.JButton();
        btn_carril_3 = new javax.swing.JButton();
        btn_carril_2 = new javax.swing.JButton();
        btn_carril_1 = new javax.swing.JButton();
        Spn_number_cars = new javax.swing.JSpinner();
        Btn_reverse = new javax.swing.JButton();
        Btn_traffic_ligth = new javax.swing.JButton();
        Btn_Simulation = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Btn_Gas_Brake.setBackground(new java.awt.Color(0, 162, 232));
        Btn_Gas_Brake.setBorder(null);
        Btn_Gas_Brake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_Gas_BrakeActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Gas_Brake, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 740, 70, 120));

        Btn_Brake.setBackground(new java.awt.Color(0, 162, 232));
        Btn_Brake.setBorder(null);
        Btn_Brake.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BrakeActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Brake, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 790, 70, 70));
        getContentPane().add(Lb_Speedometer, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 720, 150, 150));
        getContentPane().add(Lb_Car, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, 120, 120));

        btn_create_car.setFont(new java.awt.Font("Tempus Sans ITC", 1, 48)); // NOI18N
        btn_create_car.setText("Create");
        btn_create_car.setBorder(null);
        btn_create_car.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_create_carActionPerformed(evt);
            }
        });
        getContentPane().add(btn_create_car, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 890, 300, 70));

        Btn_Barrer.setBackground(new java.awt.Color(0, 162, 232));
        Btn_Barrer.setBorder(null);
        Btn_Barrer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_BarrerActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Barrer, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 740, 240, 130));

        btn_carril_10.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_10.setBorder(null);
        btn_carril_10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_10ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1186, 360, 61, 40));

        btn_carril_11.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_11.setBorder(null);
        btn_carril_11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_11ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_11, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 360, 61, 40));

        btn_carril_9.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_9.setBorder(null);
        btn_carril_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_9ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(976, 360, 61, 40));

        btn_carril_8.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_8.setBorder(null);
        btn_carril_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_8ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, 61, 40));

        btn_carril_7.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_7.setBorder(null);
        btn_carril_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_7ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(764, 360, 61, 40));

        btn_carril_6.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_6.setBorder(null);
        btn_carril_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_6ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 360, 61, 40));

        btn_carril_5.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_5.setBorder(null);
        btn_carril_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_5ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(555, 360, 61, 40));

        btn_carril_4.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_4.setBorder(null);
        btn_carril_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_4ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 360, 61, 40));

        btn_carril_3.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_3.setBorder(null);
        btn_carril_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_3ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 360, 61, 40));

        btn_carril_2.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_2.setBorder(null);
        btn_carril_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_2ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 360, 61, 40));

        btn_carril_1.setBackground(new java.awt.Color(102, 102, 102));
        btn_carril_1.setBorder(null);
        btn_carril_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_carril_1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn_carril_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 360, 61, 40));
        getContentPane().add(Spn_number_cars, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 740, 70, 30));

        Btn_reverse.setBackground(new java.awt.Color(0, 162, 232));
        Btn_reverse.setBorder(null);
        getContentPane().add(Btn_reverse, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 740, 80, 60));

        Btn_traffic_ligth.setBackground(new java.awt.Color(0, 162, 232));
        Btn_traffic_ligth.setBorder(null);
        Btn_traffic_ligth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_traffic_ligthActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_traffic_ligth, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 740, 90, 130));

        Btn_Simulation.setBackground(new java.awt.Color(0, 162, 232));
        Btn_Simulation.setBorder(null);
        getContentPane().add(Btn_Simulation, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 740, 200, 130));

        jPanel1.setOpaque(false);
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, 1130, 550));

        jFondo.setForeground(new java.awt.Color(0, 162, 232));
        jFondo.setFocusable(false);
        jFondo.setRequestFocusEnabled(false);
        jFondo.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 995));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Btn_Gas_BrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_Gas_BrakeActionPerformed
        // TODO add your handling code here:
        int new_position_tachomer = position_tachometer+1;
        if(new_position_tachomer<3){
            position_tachometer=position_tachometer+1;
            ImageIcon speedometer = new ImageIcon("src/Assets/speedometer_icon_"+position_tachometer+".png");
            Icon iconoSpeedometer = new ImageIcon(speedometer.getImage().getScaledInstance(Lb_Speedometer.getWidth(), Lb_Speedometer.getHeight(), Image.SCALE_DEFAULT));
            Lb_Speedometer.setIcon(iconoSpeedometer);
            ImageIcon car = new ImageIcon("src/Assets/car_icon_"+position_tachometer+".png");
            Icon iconoCar = new ImageIcon(car.getImage().getScaledInstance(Lb_Car.getWidth(), Lb_Car.getHeight(), Image.SCALE_DEFAULT));
            Lb_Car.setIcon(iconoCar);
        }
        else {
            System.out.println("Alcanzo la velocidad maxima");
        }
        
    }//GEN-LAST:event_Btn_Gas_BrakeActionPerformed

    private void Btn_BrakeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BrakeActionPerformed
        // TODO add your handling code here:
        int new_position_tachomer = position_tachometer;
        if(new_position_tachomer>0){
            position_tachometer=position_tachometer-1;
            ImageIcon speedometer = new ImageIcon("src/Assets/speedometer_icon_"+position_tachometer+".png");
            Icon iconoSpeedometer = new ImageIcon(speedometer.getImage().getScaledInstance(Lb_Speedometer.getWidth(), Lb_Speedometer.getHeight(), Image.SCALE_DEFAULT));
            Lb_Speedometer.setIcon(iconoSpeedometer);
            ImageIcon car = new ImageIcon("src/Assets/car_icon_"+position_tachometer+".png");
            Icon iconoCar = new ImageIcon(car.getImage().getScaledInstance(Lb_Car.getWidth(), Lb_Car.getHeight(), Image.SCALE_DEFAULT));
            Lb_Car.setIcon(iconoCar);
        }
        else {
            System.out.println("Alcanzo la velocidad minima");
        }
    }//GEN-LAST:event_Btn_BrakeActionPerformed

    private void Btn_BarrerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_BarrerActionPerformed
        // TODO add your handling code here:
        if(barrer==true){
            barrer=false;
            
            barrer_carri_1=false;
            barrer_carri_2=false;
            barrer_carri_3=false;
            barrer_carri_4=false;
            barrer_carri_5=false;
            barrer_carri_6=false;
            barrer_carri_7=false;
            barrer_carri_8=false;
            barrer_carri_9=false;
            barrer_carri_10=false;
            barrer_carri_11=false;
            
            ImageIcon barrer_lane = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril = new ImageIcon(barrer_lane.getImage().getScaledInstance(btn_carril_1.getWidth(), btn_carril_1.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_1.setIcon(iconoCarril);
            btn_carril_2.setIcon(iconoCarril);
            btn_carril_3.setIcon(iconoCarril);
            btn_carril_4.setIcon(iconoCarril);
            btn_carril_5.setIcon(iconoCarril);
            btn_carril_6.setIcon(iconoCarril);
            btn_carril_7.setIcon(iconoCarril);
            btn_carril_8.setIcon(iconoCarril);
            btn_carril_9.setIcon(iconoCarril);
            btn_carril_10.setIcon(iconoCarril);
            btn_carril_11.setIcon(iconoCarril);
            
            ImageIcon barrer_open = new ImageIcon("src/Assets/open_toll_icon.png");
            Icon iconBarrer = new ImageIcon(barrer_open.getImage().getScaledInstance(Btn_Barrer.getWidth(), Btn_Barrer.getHeight(), Image.SCALE_DEFAULT));
            Btn_Barrer.setIcon(iconBarrer);
        }else{
            barrer=true;
            
            barrer_carri_1=true;
            barrer_carri_2=true;
            barrer_carri_3=true;
            barrer_carri_4=true;
            barrer_carri_5=true;
            barrer_carri_6=true;
            barrer_carri_7=true;
            barrer_carri_8=true;
            barrer_carri_9=true;
            barrer_carri_10=true;
            barrer_carri_11=true;
            
            btn_carril_1.setIcon(null);
            btn_carril_2.setIcon(null);
            btn_carril_3.setIcon(null);
            btn_carril_4.setIcon(null);
            btn_carril_5.setIcon(null);
            btn_carril_6.setIcon(null);
            btn_carril_7.setIcon(null);
            btn_carril_8.setIcon(null);
            btn_carril_9.setIcon(null);
            btn_carril_10.setIcon(null);
            btn_carril_11.setIcon(null);
            
            
            ImageIcon barrer_close = new ImageIcon("src/Assets/close_toll_icon.png");
            Icon iconBarrer = new ImageIcon(barrer_close.getImage().getScaledInstance(Btn_Barrer.getWidth(), Btn_Barrer.getHeight(), Image.SCALE_DEFAULT));
            Btn_Barrer.setIcon(iconBarrer);
        }
    }//GEN-LAST:event_Btn_BarrerActionPerformed

    private void btn_carril_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_1ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_1==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_1.getWidth(), btn_carril_1.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_1.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_1=false;
        }else{
            btn_carril_1.setIcon(null);
            this.repaint();
            barrer_carri_1=true;
        }
    }//GEN-LAST:event_btn_carril_1ActionPerformed

    private void btn_carril_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_2ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_2==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_2.getWidth(), btn_carril_2.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_2.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_2=false;
        }else{
            btn_carril_2.setIcon(null);
            this.repaint();
            barrer_carri_2=true;
        }
    }//GEN-LAST:event_btn_carril_2ActionPerformed

    private void btn_carril_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_3ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_3==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_3.getWidth(), btn_carril_3.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_3.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_3=false;
        }else{
            btn_carril_3.setIcon(null);
            this.repaint();
            barrer_carri_3=true;
        }
    }//GEN-LAST:event_btn_carril_3ActionPerformed

    private void btn_carril_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_4ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_4==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_4.getWidth(), btn_carril_4.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_4.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_4=false;
        }else{
            btn_carril_4.setIcon(null);
            this.repaint();
            barrer_carri_4=true;
        }
    }//GEN-LAST:event_btn_carril_4ActionPerformed

    private void btn_carril_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_5ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_5==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_5.getWidth(), btn_carril_5.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_5.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_5=false;
        }else{
            btn_carril_5.setIcon(null);
            this.repaint();
            barrer_carri_5=true;
        }
    }//GEN-LAST:event_btn_carril_5ActionPerformed

    private void btn_carril_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_6ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_6==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_6.getWidth(), btn_carril_6.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_6.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_6=false;
        }else{
            btn_carril_6.setIcon(null);
            this.repaint();
            barrer_carri_6=true;
        }
    }//GEN-LAST:event_btn_carril_6ActionPerformed

    private void btn_carril_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_7ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_7==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_7.getWidth(), btn_carril_7.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_7.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_7=false;
        }else{
            btn_carril_7.setIcon(null);
            this.repaint();
            barrer_carri_7=true;
        }
    }//GEN-LAST:event_btn_carril_7ActionPerformed

    private void btn_carril_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_8ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_8==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_8.getWidth(), btn_carril_8.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_8.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_8=false;
        }else{
            btn_carril_8.setIcon(null);
            this.repaint();
            barrer_carri_8=true;
        }
    }//GEN-LAST:event_btn_carril_8ActionPerformed

    private void btn_carril_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_9ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_9==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_9.getWidth(), btn_carril_9.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_9.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_9=false;
        }else{
            btn_carril_9.setIcon(null);
            this.repaint();
            barrer_carri_9=true;
        }
    }//GEN-LAST:event_btn_carril_9ActionPerformed

    private void btn_carril_10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_10ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_10==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_10.getWidth(), btn_carril_10.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_10.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_10=false;
        }else{
            btn_carril_10.setIcon(null);
            this.repaint();
            barrer_carri_10=true;
        }
    }//GEN-LAST:event_btn_carril_10ActionPerformed

    private void btn_carril_11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_carril_11ActionPerformed
        // TODO add your handling code here:
        if(barrer_carri_11==true){
            ImageIcon carril1 = new ImageIcon("src/Assets/barrier_icon.png");
            Icon iconoCarril1 = new ImageIcon(carril1.getImage().getScaledInstance(btn_carril_11.getWidth(), btn_carril_11.getHeight(), Image.SCALE_DEFAULT));
            btn_carril_11.setIcon(iconoCarril1);
            this.repaint();
            barrer_carri_11=false;
        }else{
            btn_carril_11.setIcon(null);
            this.repaint();
            barrer_carri_11=true;
        }
    }//GEN-LAST:event_btn_carril_11ActionPerformed

    private void btn_create_carActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_create_carActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_create_carActionPerformed

    private void Btn_traffic_ligthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_traffic_ligthActionPerformed
        // TODO add your handling code here:
        
        switch (cont){
            case 0: 

                ImageIcon traffic_light_green = new ImageIcon("src/Assets/traffic_light_green_icon.png");
                Icon iconoTraffic_light_green = new ImageIcon(traffic_light_green.getImage().getScaledInstance(Btn_traffic_ligth.getWidth(), Btn_traffic_ligth.getHeight(), Image.SCALE_DEFAULT));
                Btn_traffic_ligth.setIcon(iconoTraffic_light_green);
                cont = 1;
                break;

            case 1: 

                ImageIcon traffic_light_yellow = new ImageIcon("src/Assets/traffic_light_yellow_icon.png");
                Icon iconoTraffic_light_yellow = new ImageIcon(traffic_light_yellow.getImage().getScaledInstance(Btn_traffic_ligth.getWidth(), Btn_traffic_ligth.getHeight(), Image.SCALE_DEFAULT));
                Btn_traffic_ligth.setIcon(iconoTraffic_light_yellow);
                cont = 2;
                break;

            case 2:
                
                ImageIcon traffic_light_red = new ImageIcon("src/Assets/traffic_light_red_icon.png");
                Icon iconoTraffic_light_red = new ImageIcon(traffic_light_red.getImage().getScaledInstance(Btn_traffic_ligth.getWidth(), Btn_traffic_ligth.getHeight(), Image.SCALE_DEFAULT));
                Btn_traffic_ligth.setIcon(iconoTraffic_light_red);
                cont = 0;
                break;
        }  
        
    }//GEN-LAST:event_Btn_traffic_ligthActionPerformed
 
    public void loadImage(){
        
        ImageIcon fondo = new ImageIcon("src/Assets/background_icon_0.png");
        Icon iconoFondo = new ImageIcon(fondo.getImage().getScaledInstance(jFondo.getWidth(), jFondo.getHeight(), Image.SCALE_DEFAULT));
        jFondo.setIcon(iconoFondo);
        
        ImageIcon gasBrake = new ImageIcon("src/Assets/accelerator_icon.png");
        Icon iconoGasBrake = new ImageIcon(gasBrake.getImage().getScaledInstance(Btn_Gas_Brake.getWidth(), Btn_Gas_Brake.getHeight(), Image.SCALE_DEFAULT));
        Btn_Gas_Brake.setIcon(iconoGasBrake);
        
        ImageIcon brake = new ImageIcon("src/Assets/brake_icon.png");
        Icon iconoBrake = new ImageIcon(brake.getImage().getScaledInstance(Btn_Brake.getWidth(), Btn_Brake.getHeight(), Image.SCALE_DEFAULT));
        Btn_Brake.setIcon(iconoBrake);
        
        ImageIcon car = new ImageIcon("src/Assets/car_icon_0.png");
        Icon iconoCar = new ImageIcon(car.getImage().getScaledInstance(Lb_Car.getWidth(), Lb_Car.getHeight(), Image.SCALE_DEFAULT));
        Lb_Car.setIcon(iconoCar);
        
        ImageIcon speedometer = new ImageIcon("src/Assets/speedometer_icon_0.png");
        Icon iconoSpeedometer = new ImageIcon(speedometer.getImage().getScaledInstance(Lb_Speedometer.getWidth(), Lb_Speedometer.getHeight(), Image.SCALE_DEFAULT));
        Lb_Speedometer.setIcon(iconoSpeedometer);
        
        ImageIcon reverse = new ImageIcon("src/Assets/reversed_rotating_icon.png");
        Icon iconoReverse = new ImageIcon(reverse.getImage().getScaledInstance(Btn_reverse.getWidth(), Btn_reverse.getHeight(), Image.SCALE_DEFAULT));
        Btn_reverse.setIcon(iconoReverse);
        
        ImageIcon traffic_light = new ImageIcon("src/Assets/traffic_light_red_icon.png");
        Icon iconoTraffic_light = new ImageIcon(traffic_light.getImage().getScaledInstance(Btn_traffic_ligth.getWidth(), Btn_traffic_ligth.getHeight(), Image.SCALE_DEFAULT));
        Btn_traffic_ligth.setIcon(iconoTraffic_light);
        
        ImageIcon barrer = new ImageIcon("src/Assets/open_toll_icon.png");
        Icon iconBarrer = new ImageIcon(barrer.getImage().getScaledInstance(Btn_Barrer.getWidth(), Btn_Barrer.getHeight(), Image.SCALE_DEFAULT));
        Btn_Barrer.setIcon(iconBarrer);
        
        ImageIcon simulation = new ImageIcon("src/Assets/start_icon.png");
        Icon icon_simulation = new ImageIcon(simulation.getImage().getScaledInstance(Btn_Barrer.getWidth(), Btn_Barrer.getHeight(), Image.SCALE_DEFAULT));
        Btn_Simulation.setIcon(icon_simulation);
        
        ImageIcon barrer_lane = new ImageIcon("src/Assets/barrier_icon.png");
        Icon iconoCarril = new ImageIcon(barrer_lane.getImage().getScaledInstance(btn_carril_1.getWidth(), btn_carril_1.getHeight(), Image.SCALE_DEFAULT));
        
        btn_carril_1.setIcon(iconoCarril);
        btn_carril_2.setIcon(iconoCarril);
        btn_carril_3.setIcon(iconoCarril);
        btn_carril_4.setIcon(iconoCarril);
        btn_carril_5.setIcon(iconoCarril);
        btn_carril_6.setIcon(iconoCarril);
        btn_carril_7.setIcon(iconoCarril);
        btn_carril_8.setIcon(iconoCarril);
        btn_carril_9.setIcon(iconoCarril);
        btn_carril_10.setIcon(iconoCarril);
        btn_carril_11.setIcon(iconoCarril);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Barrer;
    private javax.swing.JButton Btn_Brake;
    private javax.swing.JButton Btn_Gas_Brake;
    private javax.swing.JButton Btn_Simulation;
    private javax.swing.JButton Btn_reverse;
    public javax.swing.JButton Btn_traffic_ligth;
    private javax.swing.JLabel Lb_Car;
    private javax.swing.JLabel Lb_Speedometer;
    private javax.swing.JSpinner Spn_number_cars;
    private javax.swing.JButton btn_carril_1;
    private javax.swing.JButton btn_carril_10;
    private javax.swing.JButton btn_carril_11;
    private javax.swing.JButton btn_carril_2;
    private javax.swing.JButton btn_carril_3;
    private javax.swing.JButton btn_carril_4;
    private javax.swing.JButton btn_carril_5;
    private javax.swing.JButton btn_carril_6;
    private javax.swing.JButton btn_carril_7;
    private javax.swing.JButton btn_carril_8;
    private javax.swing.JButton btn_carril_9;
    private javax.swing.JButton btn_create_car;
    private javax.swing.JLabel jFondo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
